//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.33440
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Light_Text.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        static global::System.Resources.ResourceManager resourceMan;
        
        static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Light_Text.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡El addon se descargó correctamente!.
        /// </summary>
        internal static string addondownload {
            get {
                return ResourceManager.GetString("addondownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Addon descargado.
        /// </summary>
        internal static string addondownloadt {
            get {
                return ResourceManager.GetString("addondownloadt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar descargar el addon.
        /// </summary>
        internal static string addonerror {
            get {
                return ResourceManager.GetString("addonerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo descargar el addon.
        /// </summary>
        internal static string addonerrort {
            get {
                return ResourceManager.GetString("addonerrort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los archivos|*.
        /// </summary>
        internal static string allfilter {
            get {
                return ResourceManager.GetString("allfilter", resourceCulture);
            }
        }
		
		/// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        internal static string UC1 {
            get {
                return ResourceManager.GetString("UC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualización descargada.
        /// </summary>
        internal static string UC10 {
            get {
                return ResourceManager.GetString("UC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando desde la versión.
        /// </summary>
        internal static string UC11 {
            get {
                return ResourceManager.GetString("UC11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a la última versión disponible.
        /// </summary>
        internal static string UC12 {
            get {
                return ResourceManager.GetString("UC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar y salir.
        /// </summary>
        internal static string UC2 {
            get {
                return ResourceManager.GetString("UC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprobando actualizaciones....
        /// </summary>
        internal static string UC3 {
            get {
                return ResourceManager.GetString("UC3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo comprobar si existen actualizaciones
        ///Compruebe que dispone de conexión a internet.
        /// </summary>
        internal static string UC4 {
            get {
                return ResourceManager.GetString("UC4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha encontrado una nueva versión
        ///Haga clic en actualizar para descargarla atuomáticamente.
        /// </summary>
        internal static string UC5 {
            get {
                return ResourceManager.GetString("UC5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya está utilizando la última versión
        ///No es necesario actualizar.
        /// </summary>
        internal static string UC6 {
            get {
                return ResourceManager.GetString("UC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizando....
        /// </summary>
        internal static string UC7 {
            get {
                return ResourceManager.GetString("UC7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa se ha descargado correctamente.
        ///                
        ///Borre la versión actual y extraiga el archivo comprimido descargado en:.
        /// </summary>
        internal static string UC8 {
            get {
                return ResourceManager.GetString("UC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea abrir la carpeta?.
        /// </summary>
        internal static string UC9 {
            get {
                return ResourceManager.GetString("UC9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Caracteres:.
        /// </summary>
        internal static string chars {
            get {
                return ResourceManager.GetString("chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este archivo ha sufrido cambios y no se ha guardado todavía. ¿Desea guardarlo ahora? Si no guarda, perderá los cambios realizados en este.
        /// </summary>
        internal static string closingnosave {
            get {
                return ResourceManager.GetString("closingnosave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambios sin guardar.
        /// </summary>
        internal static string closingnosavet {
            get {
                return ResourceManager.GetString("closingnosavet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo guardar el archivo.
        /// </summary>
        internal static string couldnotsave {
            get {
                return ResourceManager.GetString("couldnotsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compilador C#.
        /// </summary>
        internal static string cscompiler {
            get {
                return ResourceManager.GetString("cscompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo actual no se ha guardado todavía.
        /// </summary>
        internal static string curnotsaved {
            get {
                return ResourceManager.GetString("curnotsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo actual está guardado.
        /// </summary>
        internal static string cursaved {
            get {
                return ResourceManager.GetString("cursaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar addon.
        /// </summary>
        internal static string downloadaddon {
            get {
                return ResourceManager.GetString("downloadaddon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo de texto plano|*.txt|Archivo de texto enriquecido|*.rtf|Archivo HTML Hypertext Markup Language|*.html;*.htm|Archivo CSS Cascade Style Sheet|*.css|Archivo PHP Hypertext Preprocessor|*.php;*.phtml|Archivo JavaScript|*.js|Archivo Visual Basics|*.vb;*.vbs|Archivo de origen C#|*.cs|Archivo batch|*.bat;*.cmd;*.nt|.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto introducido se ha encontrado.
        /// </summary>
        internal static string foundmulti1 {
            get {
                return ResourceManager.GetString("foundmulti1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a veces.
        /// </summary>
        internal static string foundmulti2 {
            get {
                return ResourceManager.GetString("foundmulti2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto introducido se ha encontrado una vez.
        /// </summary>
        internal static string foundonce {
            get {
                return ResourceManager.GetString("foundonce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto encontrado.
        /// </summary>
        internal static string foundt {
            get {
                return ResourceManager.GetString("foundt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Hola mundo!.
        /// </summary>
        internal static string helloworld {
            get {
                return ResourceManager.GetString("helloworld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang3082\deflangfe3082{\fonttbl{\f0\fswiss\fprq2\fcharset0 Segoe UI;}{\f1\froman\fprq2\fcharset2 Symbol;}}
        ///{\*\generator Riched20 6.3.9600}{\*\mmathPr\mdispDef1\mwrapIndent1440 }\viewkind4\uc1 
        ///\pard\nowidctlpar\kerning1\ul\b\f0\fs24 Ventana principal:\ulnone\b0\par
        ///
        ///\pard\nowidctlpar\sa200\sl276\slmult1\fs18 En la ventana principal puede, sin necesidad de abrir ning\&apos;fan archivo, comenzar a escribir uno nuevo. Una vez termine, puede guardarlo, y si desea, con [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string help {
            get {
                return ResourceManager.GetString("help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Líneas:.
        /// </summary>
        internal static string lines {
            get {
                return ResourceManager.GetString("lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El programa se ha cargado correctamente.
        /// </summary>
        internal static string loadsuccess {
            get {
                return ResourceManager.GetString("loadsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo guardar el archivo ya que se intentó sobreescribir un archivo oculto y no se tienen los permisos necesarios.
        /// </summary>
        internal static string neiperm {
            get {
                return ResourceManager.GetString("neiperm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El texto introducido no se ha encontrado.
        /// </summary>
        internal static string notfound {
            get {
                return ResourceManager.GetString("notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Texto no encontrado.
        /// </summary>
        internal static string notfoundt {
            get {
                return ResourceManager.GetString("notfoundt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrió un error al intentar abrir el archivo.
        /// </summary>
        internal static string openerror {
            get {
                return ResourceManager.GetString("openerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha abierto el archivo correctamente.
        /// </summary>
        internal static string opensuccess {
            get {
                return ResourceManager.GetString("opensuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesita guardar.
        /// </summary>
        internal static string saverequired {
            get {
                return ResourceManager.GetString("saverequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha guardado el archivo correctamente en.
        /// </summary>
        internal static string savesuccess {
            get {
                return ResourceManager.GetString("savesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selección:.
        /// </summary>
        internal static string selection {
            get {
                return ResourceManager.GetString("selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al guardar los ajustes.
        /// </summary>
        internal static string ssaveerror {
            get {
                return ResourceManager.GetString("ssaveerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Para compilar el archivo, antes debe guardarlo.
        ///¿Desea guardar el archivo ahora?.
        /// </summary>
        internal static string tocompile {
            get {
                return ResourceManager.GetString("tocompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compilador VB.Net.
        /// </summary>
        internal static string vbcompiler {
            get {
                return ResourceManager.GetString("vbcompiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desea descargar el addon para poder compilar en.
        /// </summary>
        internal static string wishdownload {
            get {
                return ResourceManager.GetString("wishdownload", resourceCulture);
            }
        }
    }
}
